### ISSUE TITLE
Youtube Login

### ISSUE THREAD

**Issue by oneandonlyjason** [MattJeanes/YouTubeDL#134]
Hi,

Is there a way for an OAuth Login to a Youtube Account?
Youtube often needs a Login now because it detects this as a Bot

**Comment by MattJeanes** [comment]
Unfortunately not, it's a cat and mouse game for bot / anti-bot detection with YouTube as nothing except authorised third party applications or embeds are allowed to watch YouTube outside of the YouTube website/app. They have upped there game recently so we'll have to see what happens, I do keep this app up to date from the underlying libraries so it'll pick up any improvements from that as they get published.
